* Slide 1

This video introduces random variables.
RVs are a special kind of notation for probability distributions when we are interested in numeric outcomes.
The notation with RVs is very handy and concise, but therefore also requires some getting used to.

* Slide 2

The usefulness of RV-notation is best illustrated with an example.
Suppose you contemplate whether or not to dash over to the post office to drop off a package.
You wonder whether you make it back in 15 minutes.
Suppose further that you have reliable information about the likely duration of the bike-trip (the commute), as shown here ...
You also have good and reliable probabilistic estimates for how many minutes you may have to wait in the post-office.

But you are really interested in the total time is takes to make the trip and be home again.
This means you are interested in the sum of the duration of staying in the post office and doing the commute twice.
In other words, we are interested in a numerical outcome which is the result of computing numerical outcomes from various other random events.

CLICK

Random variables help in various ways to concisely communicate about such more complex random events with numerical outcomes.

For example, ... we can write ... for the total time T being smaller than 15 minutes ...
where capital T is a random variable that is produced by summing up the outcome of other random variables, such as commute once, wait, commute again.

* Slide 3

Formally, a random variable is a function  ...

The power of RVs resides in notational uses like the following.
... is shorthand for ...

* Slide 6

Finally, another important concept to know about is the expected value of a random variable.

Suppose I do the post-office trip every day for 20 years. How much time will I have have spent on average?

We can calculate this by taking a weighted average over each logically possible duration (in minutes), weighing each numerical outcome x with its probability of occurring.

For the trip to the post-office, this amounts to about 15 minutes and a bit more than 30 seconds.

We can also compute the expected value of further numerical measures derived from a random variable.
Suppose that when you are gone from home for x minutes, you have to pay your goldfish x-squared Eurocent compensation for loneliness.

If you do your post-office trip for a very, very long time, how much money (on average) will you have paid your goldfish? - Around 2 Euro 50 cents.

Best hurry up a bit more or turn on the radio so goldfishy can hum along.
